# Generated by Django 4.0.4 on 2022-06-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0005_calcrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None, upload_to="", verbose_name="Изображение склада"
                    ),
                ),
                (
                    "number",
                    models.IntegerField(default=0, verbose_name="Номер картинки"),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imgs",
                        to="boxes.storage",
                        verbose_name="К какому складу относится",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
