# Generated by Django 4.0.4 on 2022-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_storageimage_delete_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='storage',
            name='temperature',
            field=models.IntegerField(default=15, verbose_name='Температура на складе'),
        ),
    ]
