# Generated by Django 4.0.4 on 2022-06-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0009_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="lat",
            field=models.FloatField(null=True, verbose_name="Широта"),
        ),
        migrations.AddField(
            model_name="storage",
            name="lng",
            field=models.FloatField(null=True, verbose_name="Долгота"),
        ),
    ]
