# Generated by Django 4.0.4 on 2022-06-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0011_alter_storage_lat_alter_storage_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='lng',
        ),
    ]
