# Generated by Django 4.0.4 on 2022-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="", verbose_name="аватарка"),
        ),
    ]
