# Generated by Django 4.0.4 on 2022-06-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0005_calcrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('qr_code', models.ImageField(upload_to='', verbose_name='QR-код')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='boxes.order', verbose_name='Заказ к оплате')),
            ],
        ),
    ]
