# Generated by Django 4.0.4 on 2022-06-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keystore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxkey',
            name='qr_code',
        ),
    ]
